[package]
name = "aeromod-fs"
version = "0.0.0"
authors = ["metebykl"]
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
zip = "2.6.1"
unrar = "0.5.8"

[target.'cfg(windows)'.dependencies]
junction = "1.2.0"
