[package]
name = "aeromod-settings"
version = "0.0.0"
authors = ["metebykl"]
edition = "2021"
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
